# hackOS :: picom liviano — solo lo esencial para que se vea bien sin gastar CPU/RAM
backend = "xrender";
vsync = true;

shadow = true;
shadow-radius = 8;
shadow-opacity = 0.45;
shadow-offset-x = -6;
shadow-offset-y = -6;
shadow-exclude = [
  "class_g = 'rofi'",
  "class_g = 'Dunst'"
];

fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 4;

inactive-opacity = 0.96;
active-opacity = 1.0;
frame-opacity = 0.9;
inactive-opacity-override = false;

corner-radius = 6;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur-background = false;
