general {
    colors = true
    interval = 5
    color_good = "#EA0057"
    color_degraded = "#e5c07b"
    color_bad = "#ff5555"
}

order += "wireless _first_"
order += "battery all"
order += "memory"
order += "load"
order += "tztime local"

wireless _first_ {
    format_up = "  %essid (%quality)"
    format_down = "  desconectado"
}

battery all {
    format = "%status %percentage"
    format_down = ""
    status_chr = "⚡"
    status_bat = "🔋"
    status_full = "🔌"
}

memory {
    format = " %used"
    threshold_degraded = "10%"
}

load {
    format = " %1min"
}

tztime local {
    format = " %H:%M  %d/%m"
}
