[sakura]
colorset1_fore=rgb(214,219,224)
colorset1_back=rgba(16,20,24,1)
colorset1_curs=rgb(234,0,87)
colorset1_scheme=1
colorset1_key=F1
last_colorset=1
bold_is_bright=false
scroll_lines=8000
font=JetBrainsMono Nerd Font 11
show_tab_bar=multiple
scrollbar=false
closebutton=false
tabs_on_bottom=false
less_questions=false
copy_on_select=true
disable_numbered_tabswitch=false
use_fading=false
scrollable_tabs=true
urgent_bell=Yes
audible_bell=No
blinking_cursor=No
cursor_type=VTE_CURSOR_SHAPE_BLOCK
word_chars=-,./?%&#_~:
palette=1
add_tab_accelerator=5
del_tab_accelerator=5
switch_tab_accelerator=8
move_tab_accelerator=9
copy_accelerator=5
scrollbar_accelerator=5
open_url_accelerator=5
font_size_accelerator=4
set_tab_name_accelerator=5
search_accelerator=5
add_tab_key=T
del_tab_key=W
prev_tab_key=Left
next_tab_key=Right
copy_key=C
paste_key=V
scrollbar_key=S
set_tab_name_key=N
search_key=F
increase_font_size_key=plus
decrease_font_size_key=minus
fullscreen_key=F11
set_colorset_accelerator=5
paste_button=2
menu_button=3
window_columns=100
window_rows=30
